chore (fence-config): fixing the login setup in fence-config
uc-cdis/gitops-qa pull request #1354
Opened 2021-05-03 16:41 UTC by atharvar28

Fixing the Login Configuration in `fence-config.yaml` in qa-covid19 env

2021-05-03 16:57 UTC, paulineribeyre requested changes
this is public config and should not be removed
the issue comes from somewhere else
```
Traceback (most recent call last):
  File "/fence/wsgi.py", line 3, in <module>
    app_init(app)
  File "/fence/fence/__init__.py", line 80, in app_init
    file_name=config_file_name,
  File "/fence/fence/__init__.py", line 274, in app_config
    _setup_oidc_clients(app)
  File "/fence/fence/__init__.py", line 323, in _setup_oidc_clients
    config.get("ENABLED_IDENTITY_PROVIDERS", {}).get("providers", {}).keys()
AttributeError: 'NoneType' object has no attribute 'get'
```
it looks like it doesn’t see that the `LOGIN_OPTIONS` config is set, and tries to fall back on `ENABLED_IDENTITY_PROVIDERS`
that means it can’t see the `LOGIN_OPTIONS` in the public config. So the config splitting is not working

2021-05-03 17:14 UTC, PlanXCyborg commented
# qa-jcoin.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping

2021-05-03 17:19 UTC, PlanXCyborg commented
# qa-jcoin.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping

2021-05-06 21:40 UTC, paulineribeyre approved these changes

2021-05-06 21:43 UTC, merged