update quay image version
uc-cdis/gitops-qa pull request #1486
Opened 2021-07-07 20:01 UTC by wangfan860

Link to Jira ticket if there is one: https://occ-data.atlassian.net/browse/COV-955

2021-07-07 20:02 UTC, PlanXCyborg commented
# qa-covid19.planx-pla.net/manifest.json
## :warning: Services on branch
- portal
- auspice

2021-07-07 20:18 UTC, paulineribeyre requested changes
waiting for image to be built

2021-07-08 15:09 UTC, paulineribeyre approved these changes

2021-07-09 16:54 UTC, PlanXCyborg commented
# qa-covid19.planx-pla.net/manifest.json
## :warning: Services on branch
- portal
- auspice

2021-07-09 16:54 UTC, merged